### PR TITLE
Remove redundant default value

### PR DESCRIPTION
**Pull request by ST-DDT**
This fixes an incompatibility between Battery Powered and AAI Industries.

AAI Industries assumes that either `fuel_category` or `fuel_categories` is set and overwrites `fuel_categories` with `fuel_category` if present and then deletes the `fuel_category`.
Battery Powered also assumes the same but the check is reversed.

Since AAI Industries uses final fixes vs Battery Powered's data updates, Battery Powered's changes get lost.

The mk* variants should use the same fuel category as the vanilla locomotive, so IMO there is no need to explicitly overwrite it here.

See also: https://github.com/harag-on-steam/factorio-battery-powered/pull/3

### CODE REVIEW

**Comment by RedRafe** [comment]
I guess this has been solved on Battery Powered part then?

**Comment by ST-DDT** [comment]
Yes, but you could still remove this to improve compatibility with other mods that add different fuels to the native train.
e.g. the fuel part is not really a part of this mod, or is there a reason why the value is added there?

**Comment by RedRafe** [comment]
The fuel category is still expressed (it's not that if I don't assign it, it doesn't have any).
Since the mod exposes all the prototypes alt data stage, other mods change the fuel types, it would be a good practice to edit prototypes that aren't your own at data-updates, and take care you edit them appropriately

**Comment by ST-DDT** [comment]
My point is that (AFAICT) your mod doesnt state that the new locomotives are chemical fuel only.
So the mod should not do unexpectedly change/reset which fuel a locomotive takes.
If a different mod happens to change the fuel in between to a non chemical fuel then the fuel and fuels fields differ from each other which is likely to cause incompatibilities like the one resulting in this PR (you dont clear the single fuel field, which could be considered a bug itself, even if another bug is required to make it an issue).

Additionally if a new mod adds a new fuel type you could just add it as an optional dependency to your mod and rely on load order to ensure the mod is compatible with your mod without requiring explicit compatibility code on either side.

This mod is yours, so the decision is up to you.

**Comment by RedRafe** [comment]
Sorry maybe there's been a misinterpretation.

Here is the reference to the base mod of Factorio:

https://github.com/wube/factorio-data/blob/master/base/prototypes/entity/trains.lua#L191

As you can see, the `locomotive` prototype uses explicitly `chemical` type (because that's the vanilla category of fuels). It's not that I'm specifying a strage type of fuel or anything. This is just vanilla. And each burner type must have at least 1 category assigned.

My only change is that instead of using the field "fuel" I use "fuels", as a table of (1) fuel(s). So any other fuel can be added by other mods to the list with a simple `table.insert(list, new-fuel)`

I also have explicit compat with AAI, so I, on my side, insert their fuel among the ones accepted by the locos.

But truly, BTS is just copying the vanilla prototype fuels. I create & expose all the prototypes at data stage, as early as possible, so if a mod adds its custom fuel, it should take care on its part to edit all the prototypes they want to change that property of (at data-updates) in the proper manner (i.e. checking for current categories and adding a the new ones instead of overwriting). 

I will check compatibility and add explicit one if needed, but it's not that I am doing anything strage with fuels or anything 😄

**Comment by RedRafe** [comment]
I still need to refactor 50% of the code for another PR so it will likely be fixed & checked too within the next week or so

**Comment by RedRafe** [comment]
Fixed with commit 844d184, removing field `fuel_category` as `fuel_categories` takes precedence

**Pull request closed without merging**
